#!/bin/sh -e

. ./vars.sh

DOWNLOAD_URL=${CENTOS_6_5_MINIMAL_URL}
HDD_SIZE=8192 #8 gigs by default
INSTALLER_ISO=
NAME=

while getopts :hv:s: opt; do
  case $opt in 
    h)
      echo "Usage: ./setup -v [64|65] -s [hdd size]"
      exit
      ;;
    v)
      if [ $OPTARG == 64 ] ; then
        DOWNLOAD_URL=${CENTOS_6_4_MINIMAL_URL}
        NAME="centos64-x86_64"
        INSTALLER_ISO="CentOS-6.4-x86_64-minimal.iso"
      elif [ $OPTARG = 65 ] ; then
        DOWNLOAD_URL=${CENTOS_6_5_MINIMAL_URL}
        NAME="centos65-x86_64"
        INSTALLER_ISO="CentOS-6.5-x86_64-minimal.iso"
      else
        echo "Can't support version: $OPTARG. Must be either 64 or 65"
        exit
      fi
      ;;
    s)
      HDD_SIZE=$OPTARG
      ;;
  esac
done

echo "HDD_SIZE : $HDD_SIZE"
echo "DOWNLOAD_URL : $DOWNLOAD_URL"
echo "NAME: $NAME"
echo "NAME=$NAME" > dynamic_vars.sh

# Check if the CentOS ISO is found, if not tries to download it 
if [ ! -f "${INSTALLER_PATH}${INSTALLER_ISO}" ] ; then
    if [ ! -d "${INSTALLER_PATH}" ] ; then
        mkdir -p ${INSTALLER_PATH}
    fi
    curl -Lk ${DOWNLOAD_URL} -o "${INSTALLER_PATH}${INSTALLER_ISO}"
fi

# Check if the VirtualBox Additions ISO is found

if [ ! -f "${GUESTADDITIONS}" ] ; then
    if [ -f "${GUESTADDITIONS_MAC}" ] ; then
        GUESTADDITIONS=${GUESTADDITIONS_MAC}
        echo "GUESTADDITIONS=${GUESTADDITIONS_MAC}"
    else
        echo "Can't find GuestAdditions ISO, find manually and update vars.sh with the right path"
    fi

fi


VBoxManage createvm --name ${NAME} --ostype ${TYPE} --register

VBoxManage modifyvm ${NAME} \
    --vram 12 \
    --accelerate3d off \
    --memory 613 \
    --usb off \
    --audio none \
    --boot1 disk --boot2 dvd --boot3 none --boot4 none \
    --nictype1 virtio --nic1 nat --natnet1 "${NATNET}" \
    --nictype2 virtio \
    --nictype3 virtio \
    --nictype4 virtio \
    --acpi on --ioapic off \
    --chipset piix3 \
    --rtcuseutc on \
    --hpet on \
    --bioslogofadein off \
    --bioslogofadeout off \
    --bioslogodisplaytime 0 \
    --biosbootmenu disabled

VBoxManage createhd --filename "${HDD}" --size ${HDD_SIZE} 
# Swap is recommended to be double the size of RAM.
VBoxManage createhd --filename "${HDD_SWAP}" --size 1226

VBoxManage storagectl ${NAME} \
    --name SATA --add sata --portcount 2 --bootable on

VBoxManage storageattach ${NAME} \
    --storagectl SATA --port 0 --type hdd --medium "${HDD}"
VBoxManage storageattach ${NAME} \
    --storagectl SATA --port 1 --type hdd --medium "${HDD_SWAP}"
VBoxManage storageattach ${NAME} \
    --storagectl SATA --port 2 --type dvddrive --medium "${INSTALLER_PATH}${INSTALLER_ISO}"
# Specifies Guest Additions Manually
VBoxManage storageattach ${NAME} \
    --storagectl SATA --port 3 --type dvddrive --medium "${GUESTADDITIONS}"
# Specifies Guest Additions Automatically
# Supposed to work but doesn't
# See: http://www.virtualbox.org/manual/ch08.html#vboxmanage-storageattach
# See: https://www.virtualbox.org/ticket/11165
# VBoxManage storageattach ${NAME} \
#    --storagectl SATA --port 3 --medium additions
VBoxManage startvm ${NAME} --type gui

IP=10.0.2.2

# If this directory doesn't exist the box won't be created
if [ ! -d ./boxes ] ; then
    mkdir boxes
fi

echo 'At the boot prompt, hit <TAB> and then type:'
echo " ks=http://${IP}:8081"
echo "When done typing will look like:"
echo "> vmlinuz initrd=initrd.img ks=http://${IP}:8081"
sh ./httpd.sh | nc -l 8081 >/dev/null

echo When finished:
echo "./cleanup && vagrant package --base ${NAME} --output boxes/${NAME}-`date +%Y%m%d`.box"
